kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
    #nginx namespace is only use for ingress understanding
  namespace: nginx
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-ctr
          image: himanshu31bisht/notes-app-k8s
          ports:
           - containerPort: 8000
          livenessProbe:
            httpGet: # Checks if the container is still running properly.
              path: /
              port: 8000

          readinessProbe:
            httpGet: # Checks if the container is ready to accept traffic
              path: /
              port: 8000


